steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - deploy/Dockerfile
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
serviceAccount: projects/${PROJECT_ID}/serviceAccounts/patchproof-builder@${PROJECT_ID}.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY
